### ISSUE TITLE
Docker Jetty App link to mongodb

### ISSUE THREAD

**Issue by sli4** [fhussonnois/docker-storm#14]
Docker Container Jetty publish web app met the exception, thanks for help!

com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.connection.SocketStream.open(SocketStream.java:63) ~[mongo-java-driver-3.0.3.jar:na]
        at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:114) ~[mongo-java-driver-3.0.3.jar:na]
        at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:127) ~[mongo-java-driver-3.0.3.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]
Caused by: java.net.NoRouteToHostException: No route to host
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_65]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_65]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_65]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_65]
        at com.mongodb.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:50) ~[mongo-java-driver-3.0.3.jar:na]
        at com.mongodb.connection.SocketStream.open(SocketStream.java:58) ~[mongo-java-driver-3.0.3.jar:na]
        ... 3 common frames omitted

**Comment by tjheslin1** [comment]
Try conecting to the container running mongo:

`$ docker exec -it mongo_container bash`

then run: 

`$ root@238723a36aaa:/data# cat /etc/hosts`

Look at the hostnames as a result of this command. I am running mongoDb in docker and got the following line:    (where '238723a36aaa' is the containers ID)

`172.17.0.2	238723a36aaa`

I then tried:
`new MongoClient(new ServerAddress("172.17.0.2", 27017), mongoClientBuilder.build());`

and was able to connect!

Here are my docker run commands:

`docker run --name mongo_banking -d -p 27017:27017 -v /tmp/mongo:/data/db mongo-banking`
`docker run -d -p 8085:8085 --link mongo_banking:events_store --name aggregate aggregate-image`

Note: that the "aggregate" container is running an embedded Jetty server. Similar to what you have configured I believe.

Best,
Tom

**Comment by tjheslin1** [comment]
I made an answer here:

http://stackoverflow.com/questions/38906058/unable-to-connect-to-mongodb-container-using-mongojavadriver/38906059#38906059
