### ISSUE TITLE
Multiple Supervisors

### ISSUE THREAD

**Issue by sametserpil** [fhussonnois/docker-storm#8]
How can I run multiple supervisors? I mean, each supervisor is a different docker instance.

**Comment by fhussonnois** [comment]
If you would like to run multiple supervisors on the same host, you have to mount your own storm.yaml to configure differents ports for workers `--volume /local/path/conf/:/usr/share/apache-storm/conf`

If want to deploy supervisors on multiple hosts : You can use the ambassador pattern :  
https://gist.github.com/azhawkes/34283f6209f1697d7578#file-docker-deploy-storm-cluster-sh

**Comment by sametserpil** [comment]
I get the following error:

2015-08-18 12:52:13 b.s.m.n.StormClientErrorHandler [INFO] Connection failed Netty-Client-117349db4f9c:6713
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:127) ~[na:1.7.0_79]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:645) ~[na:1.7.0_79]
        at org.apache.storm.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.Channels.connect(Channels.java:634) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.channel.AbstractChannel.connect(AbstractChannel.java:207) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229) [storm-core-0.9.4.jar:0.9.4]
        at org.apache.storm.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182) [storm-core-0.9.4.jar:0.9.4]
        at backtype.storm.messaging.netty.Client$Connector.call(Client.java:612) [storm-core-0.9.4.jar:0.9.4]
        at backtype.storm.messaging.netty.Client$Connector.call(Client.java:595) [storm-core-0.9.4.jar:0.9.4]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_79]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
